test: RadixSort.cpp CountingSort.cpp StoogeSort.cpp QuickSort.cpp HeapSort.cpp BubbleSort.cpp InsertSort.cpp MergeSort.cpp main.cpp ../Log/Log.cpp
	g++ -o $@ $^ -I../../include
.PHONY:clean
clean:
	/bin/rm -f test
